version: 2.1
setup: true
orbs:
  demo_threatrix: theatrix/demo_threatrix@dev:alpha

filters: &filters
  tags:
    only: /.*/

jobs:
  threatrix_scan:
  context:
    - oid
    docker:
      - image: circleci/openjdk:11-jdk-node
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
          

workflows:
  test-deploy:
    jobs:
      - threatrix_scan
      - demo_threatrix/install_and_scan_code:
          oid: ${oid}
          eid: ${eid}
          api_key: ${api_key}
          dir: ./
          requires:
            - threatrix_scan