version: 2.1
setup: true
orbs:
  demo_threatrix: theatrix/demo_threatrix@dev:alpha

filters: &filters
  tags:
    only: /.*/

workflows:
  install-and-run-threatrix:
    jobs:
      - demo_threatrix/install_and_scan_code:
          oid: 856cb634-419b-49a9-80aa-a9b5e287eb37
          eid: 6c7fcedb-7172-45bd-b14f-55e68e614f90
          api_key: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaXRodWItVV9rZ0RPQmUybWN3IiwiZXhwIjoxNzI1OTcxODk2LCJpYXQiOjE3MTAzMzM0OTZ9.CK5EBfbPDw2ZOnZon7St4c5ucXdX03qCkXpZ3OhdaAk
          dir: ./

# jobs:

#   demo_threatrix/install_and_scan_code:
#     docker:
#       - image: circleci/openjdk:11-jdk-node
#     steps:
#       - checkout
#       - demo_threatrix/install_and_scan_code:
#           oid: 856cb634-419b-49a9-80aa-a9b5e287eb37
#           eid: 6c7fcedb-7172-45bd-b14f-55e68e614f90
#           api_key: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaXRodWItVV9rZ0RPQmUybWN3IiwiZXhwIjoxNzI1OTcxODk2LCJpYXQiOjE3MTAzMzM0OTZ9.CK5EBfbPDw2ZOnZon7St4c5ucXdX03qCkXpZ3OhdaAk
#           dir: ./
#           requires:
#             - threatrix_scan  
          # - run:
          #     name: "echo an env var that is part of our project"
          #     command: |
          #       echo $oid # this env var must be set within the project
          #       echo $eid
          #       echo $api_key
          #       echo $env_var
          #       echo ${env_var}

# version: 2.1

# workflows:
#   test-env-vars:
#     jobs:
#       - build

# jobs:
#   build:
#     docker:
#       - image: cimg/base:2023.06
#     steps:
#       - checkout
#       - run:
#           name: "echo an env var that is part of our project"
#           command: |
#             echo $oid # this env var must be set within the project
#             echo $eid
#             echo $api_key
#             echo $env_var
#             echo ${env_var}