version: 2.1
setup: true
orbs:
  demo_threatrix: theatrix/demo_threatrix@dev:alpha

filters: &filters
  tags:
    only: /.*/

jobs:
  threatrix_scan:
    docker:
      - image: circleci/openjdk:11-jdk-node
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
          

workflows:
  test-deploy:
    jobs:
      - threatrix_scan
      - demo_threatrix/install_and_scan_code:
          oid: 856cb634-419b-49a9-80aa-a9b5e287eb37
          eid: 6c7fcedb-7172-45bd-b14f-55e68e614f90
          api_key: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaXRodWItVV9rZ0RPQmUybWN3IiwiZXhwIjoxNzI1OTcxODk2LCJpYXQiOjE3MTAzMzM0OTZ9.CK5EBfbPDw2ZOnZon7St4c5ucXdX03qCkXpZ3OhdaAk
          dir: ./
          requires:
            - threatrix_scan